import {AssignmentStatus, AssingmentItemType} from '../../src/types';

export const assignmentsDummy: AssingmentItemType[] = [
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.NOT_YET,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.NOT_YET,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.NOT_YET,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.NOT_YET,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.COMPLETED,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.COMPLETED,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.COMPLETED,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
  {
    key: '수력충전 p13~p20 풀어오기',
    title: '수력충전 p13~p20 풀어오기',
    date: '20.12.10 까지',
    onPressElement: () => console.log(),
    status: AssignmentStatus.LAST,
  },
];
