import {MarkStatus, SubmitAnswersType} from '../../src/types';

export const dummySubmitAnswers: SubmitAnswersType[] = [
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.INCORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.INCORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.INCORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.INCORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.INCORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.CORRECT,
  },
  {
    submitAnswerUID: '123',
    index: 1,
    question: '문제입니다.',
    answer: '1',
    submitValue: '1',
    markStatus: MarkStatus.INCORRECT,
  },
];
